EmployeeManagement/EmployeeManagement/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf.urls.static import static
from django.conf import settings

"""

accounts/login/ [name='login']
accounts/logout/ [name='logout']
accounts/password_change/ [name='password_change']
accounts/password_change/done/ [name='password_change_done']
accounts/password_reset/ [name='password_reset']
accounts/password_reset/done/ [name='password_reset_done']
accounts/reset/<uidb64>/<token>/ [name='password_reset_confirm']
accounts/reset/done/ [name='password_reset_complete']
"""


urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include("account.passwords.urls",namespace="account_pass")),
    path('accounts/',include('account.urls',namespace="account")),
    path('employee/',include('employee.urls',namespace="employee")),
    #path('accounts/', include('django.contrib.auth.urls')),
    path('api/users/', include("account.api.urls", namespace='users-api')),
    path('api/employees/', include("employee.api.urls", namespace='employees-api')),
]



admin.site.site_header = 'Employee Management System' 
admin.site.index_title = 'Features area'
if settings.DEBUG:
    urlpatterns = urlpatterns + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns = urlpatterns + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

EmployeeManagement/account/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf.urls.static import static

from django.conf import settings
from django.contrib.auth import views as auth_views
from . import views
app_name="account"
urlpatterns = [
   path('login/',views.login_user,name="login"),
   path('logout/',views.logout_user,name="logout"),
   path('profile/',views.getProfile,name="profile"),
   path('profile/update',views.profileUpdate,name="profile_update"),
   path('activate/<uid>/<token>', views.activate, name="activate"),
   path('create/',views.Registration,name="registration"),
   

]

EmployeeManagement/employee/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf.urls.static import static
from . import views
from django.conf import settings
app_name="employee"
urlpatterns = [
    path('create/',views.CreateEmployee,name="create"),
    path('',views.EmployeeList,name="list"),
    path('<pk>/details',views.EmployeeDetail,name="detail"),
    path('<pk>/details/update',views.EmployeeUpdate,name="update"),
]

EmployeeManagement/templates/base.html
<!DOCTYPE html>
{% load static %}
<html>
<head>
	<title></title>
	<meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
	 <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/css/bootstrap.min.css">
</head>
<body>
			{% include 'navbar.html' %}
			<div class="container">
 			{% block content %}

            {% endblock %}
        	</div>



</body>
</html>

EmployeeManagement/templates/home.html
{% extends 'base.html' %}

{% block title %}Home{% endblock %}

{% block content %}
{% if user.is_authenticated %}
  Hi {{ user.username }}!
  <p><a href="{% url 'logout' %}">logout</a></p>
  <p><a href="{% url 'password_reset' %}">reset password</a></p>
{% else %}
  <p>You are not logged in</p>
  <a href="{% url 'login' %}">login</a>
{% endif %}
{% endblock %}

EmployeeManagement/templates/navbar.html
<nav class="navbar navbar-inverse">
  <div class="container-fluid">
    <div class="navbar-header">
      <a class="navbar-brand" href="{% url 'employee:list' %}">Employee Management System</a>
    </div>
    <ul class="nav navbar-nav">
      {% if request.user.is_authenticated %}
      <li class="active"><a href="{% url 'employee:list' %}">All Employees</a></li>
      {% endif %}
    
    </ul>
    <ul class="nav navbar-nav navbar-right">
      {% if request.user.is_authenticated %}
        <li><a href="{% url 'account:profile' %}"><span class="glyphicon glyphicon-log-in"></span> Profile</a></li>
        <li>
          <a href="{% url 'account:logout' %}"><span class="glyphicon glyphicon-log-in"></span>Logout</a>
        </li>
      {% else %}
        <li><a href="{% url 'account:registration' %}"><span class="glyphicon glyphicon-user"></span> Sign Up</a></li>
      <li><a href="{% url 'account:login'%}"><span class="glyphicon glyphicon-log-in"></span> Login</a></li>

      {% endif %}
      
    </ul>
  </div>
</nav>
  

EmployeeManagement/templates/signup.html
{% extends 'base.html' %}

{% block title %}Sign Up{% endblock %}

{% block content %}
  <h2>Sign up</h2>
  <form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Sign up</button>
  </form>
{% endblock %}